const neighborhoods = {
    "bushwick": "Edgy and increasingly hip, Bushwick is an evolving, industrial area marked by imaginative street art and converted warehouses that are home to artist studios and artisanal coffee shops. Dining options span the globe, and avant-garde nightlife thrives in clubs like performance space House of Yes and quirky bars with vintage, mismatched furnishings. A few pocket parks are shaded by mature trees and have playgrounds",
    "bedford stuyvesant": "Bedford-Stuyvesant, commonly called Bed-Stuy, has been a center of African-American culture since the early 20th century, home to cultural icons from Jackie Robinson to Jay-Z. Ornate 19th-century townhouses fill the area, with indie boutiques on Tompkins Place. French bistros, Southern comfort food, and Caribbean fare define the dining scene, while diverse crowds fill hip, cozy bars, many with live music",
    "clinton hill": "The Hill, as the general area was known – with a maximum elevation of 95 feet (29 m), the highest in the area – was believed to have health benefits because many people believed that disease was more prevalent in low-lying areas. The area is named after Clinton Avenue, which in turn was named in honor of New York Governor DeWitt Clinton (1769–1828). The main thoroughfare is DeKalb Avenue. The affluent neighborhood's mixture of apartment buildings, mansions, brownstone and brick rowhouses, and the Pratt Institute and St. Joseph's College, built at various times in a number of different styles, is a great part of its charm.",
    "hells kitchen": "Adjacent to the theater district, Hell's Kitchen has long been the home of actors and arts organizations. It's also a hub of gay culture. Pre- and post-theater crowds from nearby Broadway, tourists from Times Square and workers from office high-rises jam the international restaurants, bars and pubs along 8th and 9th avenues. Farther west, along the water, Hudson River Park has landscaped walkways.",
    "astoria": "Laid-back Astoria is a multicultural neighborhood of low-rise residences and small businesses, in Queens. Known for its Greek tavernas and cafes, the area is home to a variety of traditional ethnic eateries and trendy spots. The Museum of the Moving Image, with its exhibits about film, television and digital media, is a top draw. The open-air Bohemian Beer Garden and Astoria Park hum with activity in warm weather.",
    "williamsburg": "Williamsburg is a hip neighborhood in Brooklyn that draws the young and the fashionable to its chic boutiques, trendy cafes and buzzy restaurants. Street art brightens residential thoroughfares and repurposed factories, while the waterfront provides stunning views of Manhattan and seasonal venues for outdoor concerts and food markets. Dance clubs, happening bars and music halls liven up the nightlife scene.",
    "dumbo": "Trendy Dumbo's cobblestone streets and converted Brooklyn warehouse buildings are the backdrop for independent boutiques, high-end restaurants and trendy cafes. Near the waterfront, St. Ann's Warehouse, in a former tobacco factory, is the heart of a thriving performance and gallery scene. The north end of Brooklyn Bridge Park features historic Jane’s Carousel as well as picturesque views of the Manhattan skyline",
    "flatbush": "Flatbush is a neighborhood in the New York City borough of Brooklyn. Founded in 1651 by Dutch colonists, the neighborhood, which consists of several subsections, had a population of 105,804 as of the 2010 United States Census",
    "prospect lefferts gardens": "Prospect Lefferts Gardens is a residential neighborhood in the Flatbush area of the New York City borough of Brooklyn. The community is bounded by Empire Boulevard to the north, Clarkson Avenue to the south, New York Avenue to the east, and Ocean Avenue/Prospect Park to the west",
    "south harlem": "Long known for its intimate jazz clubs, soul food institutions and African-American heritage, Harlem draws a diverse crowd of locals and visitors. Trendy eateries, stylish clubs and hip bars make for an energetic nightlife scene. The area features a mix of 19th-century brownstones and modern high-rises. Its main artery, 125th Street, is home to the iconic Apollo Theater, as well as chain stores and restaurants.",
    "central harlem": "Long known for its intimate jazz clubs, soul food institutions and African-American heritage, Harlem draws a diverse crowd of locals and visitors. Trendy eateries, stylish clubs and hip bars make for an energetic nightlife scene. The area features a mix of 19th-century brownstones and modern high-rises. Its main artery, 125th Street, is home to the iconic Apollo Theater, as well as chain stores and restaurants."
};

export default neighborhoods;